# A Python Maze

numpy is a very important Python library that allows us to work with matrices. Most Python AI libraries use numpy 

We will use numpy to represent a small 2D grid world using a matrix. Numbers in this matrix will describe what is currently occupying each place in the grid. For now, we will use the following three numbers:
* 0 to indicate an open space that the agent can traverse freely
* 1 to indicate a wall that the agent must avoid when moving
* 2 to indicate where the agent currently is
* 3 to indicate the exit of the maze that the agent needs to reach (the goal)

In [18]:
import numpy as np

# size is a tuple (x,y), where y is the number of rows 
# and y the number of columns
# x and y must be >= 3
def create_blank_maze(size):
    # here we use the numpy function zeros that initialises 
    # an x*y matrix filled with zeros
    maze = np.zeros(size, dtype=int)
    return maze

In [19]:
maze = create_blank_maze((6,6))
maze

array([[0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0]])

In [20]:
# size is a tuple (x,y), where y is the number of rows 
# and y the number of columns
# x and y must be >= 3
def create_blank_maze(size):
    # here we use the numpy function zeros that initialises 
    # an x*y matrix filled with zeros
    maze = np.zeros(size, dtype=int)
    maze[0].fill(1)
    maze[size[0]-1].fill(1)
    maze[:,0].fill(1)
    maze[:,size[1]-1].fill(1)
    return maze

In [21]:
maze = create_blank_maze((6,6))
maze

array([[1, 1, 1, 1, 1, 1],
       [1, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 1],
       [1, 1, 1, 1, 1, 1]])

In [22]:
def create_basic_maze_puzzle(size):
    maze = create_blank_maze(size)
    maze[1,1] = 2
    maze[size[0]-2,size[1]-2] = 3    
    return maze

In [23]:
maze = create_basic_maze_puzzle((8,5))
maze

array([[1, 1, 1, 1, 1],
       [1, 2, 0, 0, 1],
       [1, 0, 0, 0, 1],
       [1, 0, 0, 0, 1],
       [1, 0, 0, 0, 1],
       [1, 0, 0, 0, 1],
       [1, 0, 0, 3, 1],
       [1, 1, 1, 1, 1]])

In [24]:
def pretty_print_maze(maze):
    if not type(maze) is np.ndarray:
        return "This is not a maze"
    for row in maze:
        for element in row:
            if element == 0:
                print(" ", end=' ')
            elif element == 1:
                print("X", end=' ')  
            elif element == 2:
                print("o", end=' ') 
            elif element == 3:
                print("E", end=' ')  
            else:
                print(element, end=' ')  
        print()

In [25]:
maze = create_basic_maze_puzzle((6,6))
pretty_print_maze(maze)

X X X X X X 
X o       X 
X         X 
X         X 
X       E X 
X X X X X X 


In [26]:
def create_four_rooms_maze_puzzle(size):
    maze = create_blank_maze(size)
    
    
    # create a vertical and a horizontal wall
    if size[0] > 6:
        maze[:,size[1]//2].fill(1)
        maze[size[0]//2][size[1]//2] = 0
        maze[size[0]//2+1][size[1]//2] = 0
        maze[size[0]//2-1][size[1]//2] = 0
    if size[1] > 6:
        maze[size[0]//2].fill(1)
        maze[size[0]//2][size[1]//2] = 0
        maze[size[0]//2][size[1]//2+1] = 0
        maze[size[0]//2][size[1]//2-1] = 0
    
    maze[1,1] = 2
    maze[size[0]-2,size[1]-2] = 3
    return maze

In [27]:
maze = create_four_rooms_maze_puzzle((9,11))
pretty_print_maze(maze)

X X X X X X X X X X X 
X o       X         X 
X         X         X 
X                   X 
X X X X       X X X X 
X                   X 
X         X         X 
X         X       E X 
X X X X X X X X X X X 
