In [2]:
import numpy as np

# size is a tuple (x,y), where y is the number of rows 
# and y the number of columns
# x and y must be >= 3
def create_blank_maze(size):
    # here we use the numpy function zeros that initialises 
    # an x*y matrix filled with zeros
    maze = np.zeros(size, dtype=int)
    return maze

In [3]:
maze = create_blank_maze((6,6))
maze

array([[0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0]])

In [4]:
# size is a tuple (x,y), where y is the number of rows 
# and y the number of columns
# x and y must be >= 3
def create_blank_maze(size):
    # here we use the numpy function zeros that initialises 
    # an x*y matrix filled with zeros
    maze = np.zeros(size, dtype=int)
    maze[0].fill(1)
    maze[size[0]-1].fill(1)
    maze[:,0].fill(1)
    maze[:,size[1]-1].fill(1)
    return maze

In [5]:
maze = create_blank_maze((6,6))
maze

array([[1, 1, 1, 1, 1, 1],
       [1, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 1],
       [1, 1, 1, 1, 1, 1]])

In [6]:
def create_basic_maze_puzzle(size):
    maze = create_blank_maze(size)
    maze[1,1] = 2
    maze[size[0]-2,size[1]-2] = 3    
    return maze

In [7]:
maze = create_basic_maze_puzzle((8,5))
maze

array([[1, 1, 1, 1, 1],
       [1, 2, 0, 0, 1],
       [1, 0, 0, 0, 1],
       [1, 0, 0, 0, 1],
       [1, 0, 0, 0, 1],
       [1, 0, 0, 0, 1],
       [1, 0, 0, 3, 1],
       [1, 1, 1, 1, 1]])

In [12]:
def pretty_print_maze(maze):
    if not type(maze) is np.ndarray:
        return "This is not a maze"
    for row in maze:
        for element in row:
            if element == 0:
                print(" ", end=' ')
            elif element == 1:
                print("X", end=' ')  
            elif element == 2:
                print("o", end=' ') 
            elif element == 3:
                print("E", end=' ')  
            else:
                print(element, end=' ')  
        print()

In [13]:
maze = create_basic_maze_puzzle((6,6))
pretty_print_maze(maze)

X X X X X X 
X o       X 
X         X 
X         X 
X       E X 
X X X X X X 


In [14]:
def create_four_rooms_maze_puzzle(size):
    maze = create_blank_maze(size)
    
    
    # create a vertical and a horizontal wall
    if size[0] > 6:
        maze[:,size[1]//2].fill(1)
        maze[size[0]//2][size[1]//2] = 0
        maze[size[0]//2+1][size[1]//2] = 0
        maze[size[0]//2-1][size[1]//2] = 0
    if size[1] > 6:
        maze[size[0]//2].fill(1)
        maze[size[0]//2][size[1]//2] = 0
        maze[size[0]//2][size[1]//2+1] = 0
        maze[size[0]//2][size[1]//2-1] = 0
    
    maze[1,1] = 2
    maze[size[0]-2,size[1]-2] = 3
    return maze

In [23]:
maze = create_four_rooms_maze_puzzle((9,11))
pretty_print_maze(maze)

X X X X X X X X X X X 
X o       X         X 
X         X         X 
X                   X 
X X X X       X X X X 
X                   X 
X         X         X 
X         X       E X 
X X X X X X X X X X X 


In [17]:
import numpy as np

# size is a tuple (x,y), where y is the number of rows and y the number of columns
# x and y must be >= 3
def create_blank_maze(size):
    # here we use the numpy function zeros that initialises an x*y matrix filled with zeros
    maze = np.zeros(size, dtype=int)
    maze[0].fill(1)
    maze[size[0]-1].fill(1)
    maze[:,0].fill(1)
    maze[:,size[1]-1].fill(1)
    return maze

def create_basic_maze_puzzle(size):
    maze = create_blank_maze(size)
    maze[1,1] = 2
    maze[size[0]-2,size[1]-2] = 3    
    return maze

def create_simple_maze_puzzle(size):
    maze = create_blank_maze(size)
        
    # create some walls
    for i in range((size[0]-3)//2):
        
        maze[2+i*2].fill(1)
        
        # create some openings
        if i%2 == 0:
            maze[2+i*2][size[1]-2] = 0
        else:
            maze[2+i*2][1] = 0
        
        # if the maze is large enough, create less trivial openings
        if size[1] > 6 and i%3 == 0:
            if i%2 == 0:
                maze[2+i*2][size[1]-2] = 1
                maze[2+i*2][size[1]-5] = 0
            else:
                maze[2+i*2][1] = 1
                maze[2+i*2][4] = 0
                
    maze[1,1] = 2
    maze[size[0]-2,size[1]-2] = 3
    
    return maze

def create_four_rooms_maze_puzzle(size):
    maze = create_blank_maze(size)    
    
    # create a vertical and a horizontal wall
    if size[0] > 6:
        maze[:,size[1]//2].fill(1)
        maze[size[0]//2][size[1]//2] = 0
        maze[size[0]//2+1][size[1]//2] = 0
        maze[size[0]//2-1][size[1]//2] = 0
    if size[1] > 6:
        maze[size[0]//2].fill(1)
        maze[size[0]//2][size[1]//2] = 0
        maze[size[0]//2][size[1]//2+1] = 0
        maze[size[0]//2][size[1]//2-1] = 0
    
    maze[1,1] = 2
    maze[size[0]-2,size[1]-2] = 3
    
    return maze

def pretty_print_maze(maze):
    if not type(maze) is np.ndarray:
        return "This is not a maze"
    for row in maze:
        for element in row:
            if element == 0:
                print(" ", end=' ')
            elif element == 1:
                print("X", end=' ')  
            elif element == 2:
                print("o", end=' ') 
            elif element == 3:
                print("E", end=' ')  
            else:
                print(element, end=' ')  
        print()

In [20]:
all_actions = ["UP", "DOWN", "LEFT", "RIGHT"]

maze = create_simple_maze_puzzle((9,12))
pretty_print_maze(maze)
maze

X X X X X X X X X X X X 
X o                   X 
X X X X X X X   X X X X 
X                     X 
X   X X X X X X X X X X 
X                     X 
X X X X X X X X X X   X 
X                   E X 
X X X X X X X X X X X X 


array([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 3, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]])

In [24]:
def apply_action(maze, action):
    x,y = np.where(maze == 2)
    pr = x[0]
    pc = y[0]
    movement_tuple = (0,0)
    if action == "UP":
        movement_tuple = (-1,0)
    elif action == "DOWN":
        movement_tuple = (1,0)
    elif action == "LEFT":
        movement_tuple = (0,-1)
    elif action == "RIGHT":
        movement_tuple = (0,1)
    if action == "UP" or action == "DOWN" or action == "LEFT" or action == "RIGHT":    
        if maze[pr+movement_tuple[0],pc+movement_tuple[1]] == 1:
            return None
        else:
            new_maze = np.copy(maze)
            new_maze[pr+movement_tuple[0],pc+movement_tuple[1]] = 2
            new_maze[pr,pc] = 0
            return new_maze

In [28]:
maze_after = apply_action(maze,"DOWN")
pretty_print_maze(maze_after)
maze_after

X X X X X X X X X X X 
X         X         X 
X o       X         X 
X                   X 
X X X X       X X X X 
X                   X 
X         X         X 
X         X       E X 
X X X X X X X X X X X 


array([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1],
       [1, 2, 0, 0, 0, 1, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 1, 1, 1, 0, 0, 0, 1, 1, 1, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 1, 0, 0, 0, 3, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]])

In [29]:
def is_action_valid(maze, action):
    return type(apply_action(maze, action)) is np.ndarray

def apply_actions(maze, actions, print_actions = False):
    new_maze = np.copy(maze)
    if print_actions:
        pretty_print_maze(maze)
    for action in actions:
        new_maze = apply_action(new_maze, action)
        if not type(new_maze) is np.ndarray:
            return None
        if print_actions:
            print('\nAction: '+action)
            pretty_print_maze(new_maze)
    return new_maze

In [31]:
apply_actions(maze,["RIGHT", "DOWN", "RIGHT", "DOWN"], print_actions = True)

X X X X X X X X X X X 
X o       X         X 
X         X         X 
X                   X 
X X X X       X X X X 
X                   X 
X         X         X 
X         X       E X 
X X X X X X X X X X X 

Action: RIGHT
X X X X X X X X X X X 
X   o     X         X 
X         X         X 
X                   X 
X X X X       X X X X 
X                   X 
X         X         X 
X         X       E X 
X X X X X X X X X X X 

Action: DOWN
X X X X X X X X X X X 
X         X         X 
X   o     X         X 
X                   X 
X X X X       X X X X 
X                   X 
X         X         X 
X         X       E X 
X X X X X X X X X X X 

Action: RIGHT
X X X X X X X X X X X 
X         X         X 
X     o   X         X 
X                   X 
X X X X       X X X X 
X                   X 
X         X         X 
X         X       E X 
X X X X X X X X X X X 

Action: DOWN
X X X X X X X X X X X 
X         X         X 
X         X         X 
X     o             X 
X X X X       X X X X 

array([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1],
       [1, 0, 0, 2, 0, 0, 0, 0, 0, 0, 1],
       [1, 1, 1, 1, 0, 0, 0, 1, 1, 1, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 1, 0, 0, 0, 3, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]])